cds/modules/invenio_deposit/views/ui.py
# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""Deposit UI."""


from copy import deepcopy

from cds.modules.ldap.decorators import require_upload_permission
from flask import Blueprint, current_app, render_template, request
from flask_login import login_required
from invenio_pidstore.errors import PIDDeletedError
from invenio_records_ui.signals import record_viewed

from ..proxies import current_deposit


def create_blueprint(endpoints):
    """Create Invenio-Deposit-UI blueprint.

    See: :data:`invenio_deposit.config.DEPOSIT_RECORDS_UI_ENDPOINTS`.

    :param endpoints: List of endpoints configuration.
    :returns: The configured blueprint.
    """
    from invenio_records_ui.views import create_url_rule

    blueprint = Blueprint(
        "invenio_deposit_ui",
        __name__,
        static_folder="../static",
        template_folder="../templates",
        url_prefix="",
    )

    @blueprint.errorhandler(PIDDeletedError)
    def tombstone_errorhandler(error):
        """Render tombstone page."""
        return (
            render_template(
                current_app.config["DEPOSIT_UI_TOMBSTONE_TEMPLATE"],
                pid=error.pid,
                record=error.record or {},
            ),
            410,
        )

    for endpoint, options in (endpoints or {}).items():
        options = deepcopy(options)
        options.pop("jsonschema", None)
        options.pop("schemaform", None)
        blueprint.add_url_rule(**create_url_rule(endpoint, **options))

    @blueprint.route("/deposit")
    @login_required
    @require_upload_permission()
    def index():
        """List user deposits."""
        return render_template(current_app.config["DEPOSIT_UI_INDEX_TEMPLATE"])

    @blueprint.route("/deposit/new")
    @login_required
    @require_upload_permission()
    def new():
        """Create new deposit."""
        deposit_type = request.values.get("type")
        return render_template(
            current_app.config["DEPOSIT_UI_NEW_TEMPLATE"],
            record={"_deposit": {"id": None}},
            jsonschema=current_deposit.jsonschemas[deposit_type],
            schemaform=current_deposit.schemaforms[deposit_type],
        )

    return blueprint


def default_view_method(pid, record, template=None):
    """Default view method.

    Sends ``record_viewed`` signal and renders template.
    """
    record_viewed.send(
        current_app._get_current_object(),
        pid=pid,
        record=record,
    )

    deposit_type = request.values.get("type")

    return render_template(
        template,
        pid=pid,
        record=record,
        jsonschema=current_deposit.jsonschemas[deposit_type],
        schemaform=current_deposit.schemaforms[deposit_type],
    )

cds/modules/invenio_deposit/templates/invenio_deposit/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    {%- block page_body %}{%- endblock page_body %}
  </body>
</html>

cds/modules/invenio_deposit/templates/invenio_deposit/edit.html
{#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.
#}

{%- extends config.DEPOSIT_BASE_TEMPLATE %}

{%- block page_body %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div id="invenio-records">
          <invenio-records
            {% if pid %}
              initialization="{{ config.DEPOSIT_RECORDS_API.format(pid_value=pid.pid_value) }}"
            {% else %}
              initialization="{{ config.DEPOSIT_SEARCH_API }}"
            {% endif %}
            response-params='{{ config.DEPOSIT_RESPONSE_MESSAGES | tojson }}'
            extra-params='{"headers":{"Content-Type": "application/json"}}'
            form="{{ url_for('static', filename=schemaform) }}"
            record='{{ record | tojson }}'
            schema="{{ url_for('invenio_jsonschemas.get_schema', schema_path=jsonschema) }}">
            <invenio-records-loading
              template="{{ url_for('static', filename='node_modules/invenio-records-js/dist/templates/loading.html') }}">
            </invenio-records-loading>
            <invenio-records-alert
              template="{{ url_for('static', filename='node_modules/invenio-records-js/dist/templates/alert.html') }}">
            </invenio-records-alert>
            <invenio-records-actions
              template="{{ url_for('static', filename=config.DEPOSIT_UI_JSTEMPLATE_ACTIONS) }}">
            </invenio-records-actions>
            <!-- <invenio-records-form
              form-templates='{{ config.DEPOSIT_FORM_TEMPLATES | tojson }}'
              form-templates-base="{{ url_for('static', filename=config.DEPOSIT_FORM_TEMPLATES_BASE) }}"
              template="{{ url_for('static', filename=config.DEPOSIT_UI_JSTEMPLATE_FORM) }}">
            </invenio-records-form> -->
          </invenio-records>
          <invenio-files-uploader
            method="PUT"
            endpoint="/api/files"
            {% if pid %}
              action="{{ config.DEPOSIT_RECORDS_API|format(pid_value=pid.pid_value) }}"
            {% else %}
              initialization="{{ config.DEPOSIT_SEARCH_API }}"
            {% endif %}
            extra-params='{"headers":{"Content-Type": "application/json"}}'
          >
            <invenio-files-upload-zone
              template="{{ url_for('static', filename='node_modules/invenio-files-js/dist/templates/upload.html') }}">
            </invenio-files-upload-zone>
            <invenio-files-list
              template="{{ url_for('static', filename='node_modules/invenio-files-js/dist/templates/list.html') }}"
            ></invenio-files-list>
        </invenio-files-uploader>
        </div>
      </div>
    </div>
  </div>
{%- endblock %}

cds/modules/invenio_deposit/templates/invenio_deposit/index.html
{#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.
#}

{%- extends config.DEPOSIT_BASE_TEMPLATE %}

{%- block body_inner %}
<div id="invenio-search">
  <invenio-search
   search-endpoint="{{ config.DEPOSIT_SEARCH_API }}"
   search-headers='{"Accept": "{{ config.DEPOSIT_SEARCH_MIMETYPE|default('application/json')}}"}'
  >
  {{super()}}
  </invenio-search>
</div>
{%- endblock body_inner %}

{%- block page_body %}
<div class="container search-page">
  {%- block search_body %}
    <div class="row">
      <div class="col-md-8 col-sm-8 col-xs-8">
        <div class="row">
          {%- block search_bar %}
          <div class="col-md-8">
            <invenio-search-bar
            template="{{ url_for('static', filename='templates/invenio_deposit/searchbar.html') }}"
            placeholder="{{ _('Search uploads...') }}">
            </invenio-search-bar>
          </div>
          {%- endblock search_bar %}
          {%- block search_loading %}
          <div class="col-md-4">
            <invenio-search-loading
              template="{{ url_for('static', filename=config.SEARCH_UI_JSTEMPLATE_LOADING) }}"
              message="{{ _('Loading...') }}">
            </invenio-search-loading>
          </div>
          {%- endblock search_loading %}
        </div>
      </div>
      {%- block new_upload %}
      <div class="col-md-offset-2 col-md-2 col-sm-4 col-xs-4">
        <a class="btn btn-success btn-block" href="{{ url_for('invenio_deposit_ui.new') }}">
          <i class="pull-left glyphicon glyphicon-upload"></i> {{ _('New Upload') }}
        </a>
      </div>
      {%- endblock new_upload %}
    </div>

    {%- block search_error %}
    <invenio-search-error
      template="{{ url_for('static', filename='templates/invenio_search_ui/error.html') }}"
      message="{{ _('Search failed.') }}">
    </invenio-search-error>
    {%- endblock search_error %}

    <div class="panel panel-default deposit-panel">
      <div class="panel-heading">
        {%- block search_facets %}
        <invenio-search-facets
        template="{{ url_for('static', filename='templates/invenio_deposit/selectstatus.html') }}">
        </invenio-search-facets>
        {%- endblock search_facets %}
        {%- block search_sort %}
        <div class="pull-right form-inline">
          <div class="form-group">
          {%- set sort_options = config.get('DEPOSIT_REST_SORT_OPTIONS', {}).get(config.DEPOSIT_UI_SEARCH_INDEX) %}
          {%- if sort_options %}
            <label>{{ _('Sort') }}</label>
            {%- block search_sort_select scoped %}
            <invenio-search-select-box
              sort-key="sort"
              available-options='{{ sort_options|format_sortoptions|safe }}'
              template="{{ url_for('static', filename='templates/invenio_deposit/selectbox.html') }}"
              >
            </invenio-search-select-box>
            {%- endblock search_sort_select %}
            {%- block search_sort_order scoped %}
            <invenio-search-sort-order
            sort-key="sort"
            template="{{ url_for('static', filename='templates/invenio_deposit/togglebutton.html') }}"
            >
            </invenio-search-sort-order>
            {%- endblock search_sort_order %}
          {%- endif %}
          </div>
        </div>
        {%- endblock search_sort %}
      </div>
      {%- block search_results %}
      <invenio-search-results
        class="list-group"
        template="{{ url_for('static', filename='templates/invenio_deposit/results.html') }}">
      </invenio-search-results>
      {%- endblock search_results %}
    </div>
    {%- block search_pagination_bottom %}
    <div align="center">
      <invenio-search-pagination
        template="{{ url_for('static', filename='templates/invenio_search_ui/pagination.html') }}">
      </invenio-search-pagination>
    </div>
    {%- endblock search_pagination_bottom %}
  {%- endblock search_body %}
</div>
{%- endblock page_body -%}

cds/modules/invenio_deposit/templates/invenio_deposit/tombstone.html
{#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.
#}
{%- extends config.RECORDS_UI_TOMBSTONE_TEMPLATE %}