cds/modules/deposit/loaders/__init__.py
# -*- coding: utf-8 -*-
#
# This file is part of CERN Document Server.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02D111-1307, USA.

"""Deposit loaders."""

from cds.modules.deposit.loaders.loader import marshmallow_loader
from cds.modules.records.serializers.schemas.project import ProjectSchema
from cds.modules.records.serializers.schemas.video import VideoSchema

# Loaders for project schema.
project_loader = marshmallow_loader(ProjectSchema)
partial_project_loader = marshmallow_loader(ProjectSchema, partial=True)

# Loaders for video schema.
video_loader = marshmallow_loader(VideoSchema)
partial_video_loader = marshmallow_loader(VideoSchema, partial=True)

cds/modules/deposit/schemas/__init__.py
"""CDS Videos deposit JSON Schemas."""

cds/modules/deposit/views.py
# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016, 2019 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""CDS interface."""


from cds.modules.ldap.decorators import require_upload_permission
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    redirect,
    render_template,
    url_for,
)
from flask_security import current_user, login_required
from invenio_db import db
from invenio_pidstore.models import PersistentIdentifier, PIDStatus
from invenio_records_ui.signals import record_viewed
from invenio_sequencegenerator.api import Sequence, Template

from ..records.permissions import (
    has_admin_permission,
    has_read_record_eos_path_permission,
)
from ..records.providers import CDSReportNumberProvider
from .api import CDSDeposit, Video
from .form import MintReportNumber, ReserveReportNumberForm
from .resolver import get_video_pid

blueprint = Blueprint(
    "cds_deposit", __name__, template_folder="templates", static_folder="static"
)


def project_view(pid, record, template=None, **kwargs):
    """Edit project view."""
    record_viewed.send(
        current_app._get_current_object(),
        pid=pid,
        record=record,
    )
    return render_template(
        template,
        pid=pid,
        record=record,
        record_type="project",
        current_user_email=current_user.email,
    )


@blueprint.app_template_filter()
def check_avc_permissions(record):
    """Check if user has permission to see EOS video library path."""
    return has_read_record_eos_path_permission(current_user, record)


@blueprint.app_template_global()
def has_avc_permission():
    """Test if current has has AVC permission."""
    return has_read_record_eos_path_permission(current_user, record=None)


@blueprint.app_template_filter()
def check_if_super_admin(record):
    """Check if user is super admin."""
    return has_admin_permission(current_user, record)


@blueprint.app_template_filter("tolinksjs")
def to_links_js(pid, deposit=None, dep_type=None):
    """Get API links."""
    if not isinstance(deposit, CDSDeposit):
        return []

    if dep_type:
        api_endpoint = current_app.config["DEPOSIT_RECORDS_API"]
        self_url = api_endpoint.format(pid_value=pid.pid_value, type=dep_type)
    else:
        api_endpoint = current_app.config["DEPOSIT_RECORDS_API_DEFAULT"]
        self_url = api_endpoint.format(pid_value=pid.pid_value)

    return {
        "self": self_url,
        "html": url_for(
            "invenio_deposit_ui.{}".format(dep_type or pid.pid_type),
            pid_value=pid.pid_value,
        ),
        "bucket": current_app.config["DEPOSIT_FILES_API"]
        + "/{0}".format(str(deposit.files.bucket.id)),
        "discard": self_url + "/actions/discard",
        "edit": self_url + "/actions/edit",
        "publish": self_url + "/actions/publish",
        "files": self_url + "/files",
    }


@blueprint.route("/deposit/reportnumbers/new", methods=["GET", "POST"])
@login_required
@require_upload_permission()
def reserve_report_number():
    """Form to reserver a new report number."""
    if not has_read_record_eos_path_permission(current_user, None):
        # Only AV CERN team has access to this feature
        abort(403)

    form = ReserveReportNumberForm()

    if form.validate_on_submit():
        data = form.data
        if not data.get("project_number"):
            # reserve project first
            project_counter = Sequence("project-v1_0_0", **data).next()
            CDSReportNumberProvider.create(object_type="rec", pid_value=project_counter)
        else:
            # Get the project template
            template = Template("project-v1_0_0")
            counter = template.model.counter(**data)
            project_counter = counter.template_instance.format(
                counter=data["project_number"]
            )

        video_sequence = Sequence("video-v1_0_0", **{"project-v1_0_0": project_counter})
        video_counter = video_sequence.next()
        CDSReportNumberProvider.create(object_type="rec", pid_value=video_counter)
        flash("New report number reserved {0}.".format(video_counter))

        db.session.commit()

        return redirect(url_for("invenio_deposit_ui.index"))

    return render_template("cds_deposit/reserve_report_number.html", form=form)


@blueprint.route(
    "/deposit/reportnumbers/assign/<string:depid>", methods=["GET", "POST"]
)
@login_required
@require_upload_permission()
def assign_report_number(depid):
    """Form to reserver a new report number."""
    if not has_read_record_eos_path_permission(current_user, None):
        # Only AV CERN team has access to this feature
        abort(403)

    video_uuid = get_video_pid(pid_value=depid).object_uuid
    video = Video.get_record(video_uuid)

    if video.get("report_number"):
        flash(
            "This video already has a report number assigned {0}".format(
                video["report_number"][0]
            ),
            category="error",
        )
        return redirect(
            url_for("invenio_deposit_ui.project", pid_value=video.get("_project_id"))
        )

    possible_report_numbers = _get_report_numbers(video)
    form = MintReportNumber()
    form.report_number.choices = [("", "")]  # Default choice
    form.report_number.choices.extend([(rn, rn) for rn in possible_report_numbers])

    if form.validate_on_submit():
        try:
            video.assign_report_number(form.report_number.data)
            db.session.commit()
            flash("Report number assigned: {0}".format(video["report_number"]))
            return redirect(
                url_for(
                    "invenio_deposit_ui.project", pid_value=video.get("_project_id")
                )
            )
        except Exception as e:
            db.session.rollback()
            flash("An error has occurred: {0}".format(e), category="error")

    return render_template(
        "cds_deposit/assign_report_number.html", video=video, form=form
    )


def _get_report_numbers(video):
    """Get the list of report numbers matching the query send as ULR args."""
    project_rn = video.project.report_number
    category = video.project.get("category")
    type_ = video.project.get("type")

    if project_rn:
        regex = "^{0}-\\d+$".format(project_rn)
    elif category and type_:
        regex = "^{0}-{1}-\\d+-\\d+-\\d+$".format(category, type_)
    else:
        return []

    rns = PersistentIdentifier.query.filter(
        PersistentIdentifier.status == PIDStatus.RESERVED,
        PersistentIdentifier.pid_value.op("~")(regex),
    )
    return [rn.pid_value for rn in rns]

cds/modules/deposit/templates/cds_deposit/assign_report_number.html
{# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2019 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.
#}

{% extends config.BASE_TEMPLATE %}

{%- set title_prefix = _('Assign Report Number') -%}
{%- from "invenio_userprofiles/settings/_macros.html" import render_field -%}
{%- from "invenio_accounts/_macros.html" import form_errors -%}

{%- block page_body -%}
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3 class="text-center panel-free-title">
          {{_('Assign Report Number') }}</h3>
        <p>You will be assigning a report number to your video {{ video.title.title }}. </p>
        <p>This action can <strong>not be undone</strong>.</p>
        <form action="{{ url_for('cds_deposit.assign_report_number', depid=video._deposit.id ) }}"
          method="POST" name="new-reportnumber">
          {{form_errors(form)}}
          {{ form.csrf_token }}
          {{ render_field(form.report_number) }}
          <div class="form-group pull-right">
            <a href="{{ url_for('invenio_deposit_ui.project', pid_value=video._project_id) }}"
               class="btn btn-default">
              <i class="fa fa-times"></i> {{ _('Cancel') }}
            </a>
            <button type="submit" name="submit" class="btn btn-primary">
              <i class="fa fa-check"></i>{{ _('Assign') }}
            </button>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>
{%- endblock -%}

cds/modules/deposit/templates/cds_deposit/edit.html
{%- extends "cds_theme/page.html" %}
{%- set title_prefix = record.get('title', {}).get('title', 'Project') -%}
{%- set container_class = '{{container_class}} cds-max-fluid-width' -%}
{%- set body_css_classes = ['flex-container', 'bootstrap-padding-top', 'cds-deposit-edit-page'] -%}

{%- block css %}
    {{ super() }}
    <style>
      body {
        background-color: #eee;
      }
    </style>
{%- endblock css %}

{%- block javascript %}
  <script type="text/javascript">
  // CKEDITOR static location
  window.CKEDITOR_BASEPATH = '{{url_for("static", filename="ckeditor/", _external=True)}}';
  </script>
  {{ super() }}
  {{ webpack["cds_deposit_app.js"] }}
  {#  <script type="text/javascript">
    angular.element(document).ready(function() {
      angular.bootstrap(
        document.getElementById('cds-deposit'), ['cds', 'cdsDeposit', 'ngModal']
      );
    }, {strictDi: true});
  $(document).ready(function() {
    $('.dropdown-toggle').dropdown();
  });
  </script> #}
{%- endblock javascript %}

{%- block page_header %}
  {%- set suggest_app = false -%}
  {% include "cds_home/header.html" %}
{%- endblock page_header %}

{%- block page_body %}
<div id="cds-deposit" class="flex-item">
  <cds-deposits
      {% if pid %}
        project-links='{{pid|tolinksjs(record, dep_type=record_type)|tojson}}'
      {% else %}
        project-init="/api/deposits/project/"
      {% endif %}
      video-extensions=".mp4,.mkv,.mov,.m4v"
      project-schema="{{ url_for('invenio_jsonschemas.get_schema', schema_path=config.DEPOSIT_JSONSCHEMA.project, _external=True) }}"
      project-form="{{ url_for('static', filename=config.DEPOSIT_DEFAULT_SCHEMAFORM) }}"
      video-init="/api/deposits/video/"
      video-schema="{{ url_for('invenio_jsonschemas.get_schema', schema_path=config.DEPOSIT_JSONSCHEMA.video, _external=True) }}"
      video-form="{{ url_for('static', filename='json/cds_deposit/forms/video.json') }}"
      template="{{ url_for('static', filename='templates/cds_deposit/deposits.html') }}"
      show-avc-restricted-fields="{{ record | check_avc_permissions | lower }}"
      is-super-admin="{{ record | check_if_super_admin | lower }}"
      current-user-email="'{{ current_user_email | lower}}'"
  >
  </cds-deposits>
  <input type="hidden" id="max-n-videos-per-project" value="{{ config.DEPOSIT_PROJECT_MAX_N_VIDEOS }}" />
</div>
{%- endblock %}

cds/modules/deposit/templates/cds_deposit/header.html
{%- extends "cds_theme/header.html" %}

{%- block navbar_search %}
  <invenio-search-bar
    template="{{ url_for('static', filename='templates/cds_deposit/searchbar.html') }}"
    placeholder="{{ search_input_placeholder|default(_('Deposit')) }}">
  </invenio-search-bar>
  {%- endblock navbar_search %}

cds/modules/deposit/templates/cds_deposit/index.html
{%- extends "cds_theme/page.html" %}
{%- set title_prefix = _('Deposits') -%}
{%- block css %}
  {{ super() }}
  {{webpack['search_ui_theme.css']}}
{%- endblock css %}

{%- block javascript %}
  {{ super() }}
  {{ webpack['cds_theme_app.js'] }}
  {{ webpack['cds_search_ui_app.js'] }}
  {{ webpack["cds_deposit_app.js"] }}
  {<script>
    angular.element(document).ready(function() {
      angular.bootstrap(
        document.getElementById("cds-deposit-index"), [
          'cds',
          'angular-loading-bar',
          'ngDialog',
          'invenioSearch',
          'cdsDeposit',
        ], { strictDi: true }
      );
    });
    $(document).ready(function() {
      $('.dropdown-toggle').dropdown();
    })
  </script>
{%- endblock javascript %}

{%- block body_inner %}
<div id="cds-deposit-index">
  <invenio-search
   search-endpoint="{{ config.DEPOSIT_SEARCH_API }}"
   search-headers='{"Accept": "{{ config.DEPOSIT_SEARCH_MIMETYPE|default('application/json')}}"}'
  >
  {{super()}}
  </invenio-search>
</div>
{%- endblock body_inner %}

{%- block page_header %}
  {%- set suggest_app = false -%}
  {% include "cds_home/header.html" %}
{%- endblock page_header %}

{%- block page_body %}
<div class="{{container_class}} search-page flex-item py-20">
    <div class="row">
      <div class="col-md-offset-3 col-md-9">
        <div class="row">
          <div class="col-md-5">
            <invenio-search-bar
            template="{{ url_for('static', filename='templates/invenio_deposit/searchbar.html') }}"
            placeholder="{{ _('Search uploads...') }}">
            </invenio-search-bar>

          </div>
          <div class="col-md-2">
            <invenio-search-loading
              template="{{ url_for('static', filename=config.SEARCH_UI_JSTEMPLATE_LOADING) }}"
              message="{{ _('Loading...') }}">
            </invenio-search-loading>
          </div>
          <div class="col-md-7 text-right">
             {%- set sort_options = config.get('DEPOSIT_REST_SORT_OPTIONS', {}).get(config.DEPOSIT_UI_SEARCH_INDEX) %}
             <invenio-search-select-box
               sort-key="sort"
               available-options='{{ sort_options|format_sortoptions|safe }}'
               template="{{ url_for('static', filename='templates/cds_deposit/selectbox.html') }}"
               >
             </invenio-search-select-box>
             {%- if has_avc_permission() %}
             <a class="btn btn-warning" href="{{ url_for('cds_deposit.reserve_report_number') }}">
               <i class="glyphicon glyphicon-magnet"></i> {{ _('Reserve Report Number') }}
             </a>
             {%- endif %}
            <a class="btn btn-success" href="{{ url_for('invenio_deposit_ui.new', type='project') }}">
              <i class="glyphicon glyphicon-upload"></i> {{ _('New Upload') }}
            </a>
          </div>
        </div>
      </div>
      <invenio-search-error
        template="{{ url_for('static', filename=config.SEARCH_UI_JSTEMPLATE_ERROR) }}"
        message="{{ _('Search failed.') }}">
      </invenio-search-error>
    </div> <!-- ./row -->
    <div class="row">
      <div class="col-md-3">
          <invenio-search-facets
          template="{{ url_for('static', filename='templates/cds_deposit/search/facets.html') }}">
          </invenio-search-facets>
      </div><!-- ./col-md-3 -->
      <div class="col-md-9">
          <div id="cds-deposit-ie-warning" class="hidden">
            <div class="alert alert-danger" role="alert">IE browser below <b>Edge</b> is not supported! Please use the latest version of Safari, Chrome or Firefox.</div>
          </div>
          <invenio-search-results
            class="list-group"
            template="{{ url_for('static', filename='templates/cds_deposit/search/results.html') }}">
          </invenio-search-results>
        <div class="text-center my-20">
          <invenio-search-pagination
            template="{{ url_for('static', filename='templates/invenio_search_ui/pagination.html') }}">
          </invenio-search-pagination>
        </div>
      </div> <!-- ./col-md-9 -->
    </div> <!-- ./row -->
</div>
{%- endblock page_body -%}

cds/modules/deposit/templates/cds_deposit/reserve_report_number.html
{# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2019 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.
#}

{% extends config.BASE_TEMPLATE %}

{%- set title_prefix = _('Reserve Report Number') -%}
{%- from "invenio_userprofiles/settings/_macros.html" import render_field -%}
{%- from "invenio_accounts/_macros.html" import form_errors -%}

{%- block page_body -%}
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3 class="text-center panel-free-title">
          {{_('Obtain a new report number') }}</h3>
        <form action="{{ url_for('cds_deposit.reserve_report_number') }}"
          method="POST" name="new-reportnumber">
          {{form_errors(form)}}
          {{ form.csrf_token }}
          {{ render_field(form.year) }}
          {{ render_field(form.category) }}
          {{ render_field(form.type) }}
          {{ render_field(form.project_number) }}
          <div class="form-group pull-right">
            <a href="{{ url_for('invenio_deposit_ui.index') }}" class="btn btn-default">
              <i class="fa fa-times"></i> {{ _('Cancel') }}
            </a>
            <button type="submit" name="submit" class="btn btn-primary">
              <i class="fa fa-check"></i>{{ _('Obtain') }}
            </button>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>
{%- endblock -%}